version: 0.2
phases:
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:
      - echo 'Compiling the Java Code'
      - echo 'builspec2'
      - npm install jest-junit --save-dev
      - npx jest --listTests
      - npx jest --runInBand --coverage
      - ls
      - pwd
      - cd _tests_
      - ls
  post_build:
    commands:
      - echo "Would deploy here"
      
reports:
  test-reports-wo-fo:
    files:
      - "**/*"
    base-directory: 'test-reports-wo-fo'
    file-format: JunitXml

artifacts:
  files:
    - 'test-reports-wo-fo/**/*'
    - 'coverage-reports/**/*'
  name: build-reports-$(date +%Y-%m-%d)
  s3-prefix: reports-test-cov/
